import { Project } from "../Projet";
import { Remarque } from "../Remarque";

export class Etape6 {
    constructor(
        public id: number,
        public augmentation: number,
        public justification: string,
        public chargesTotal: number,
        public cumulativeTotal: number,
        public terrain: number,
        public equipementProduction: number,
        public materielTransport: number,
        public mobilier: number,
        public frais: number,
        public chargesTotal1: number,
        public chargesTotal2: number,
        public chargesTotal3: number,
        public chargesTotal4: number,
        public chargesTotal5: number,
        public rbe1: number,
        public rbe2: number,
        public rbe3: number,
        public rbe4: number,
        public rbe5: number,
        public frais1: number,
        public frais2: number,
        public frais3: number,
        public frais4: number,
        public frais5: number,
        public beneficeBrut1: number,
        public beneficeBrut2: number,
        public beneficeBrut3: number,
        public beneficeBrut4: number,
        public beneficeBrut5: number,
        public impot1: number,
        public impot2: number,
        public impot3: number,
        public impot4: number,
        public impot5: number,
        public beneficeNet1: number,
        public beneficeNet2: number,
        public beneficeNet3: number,
        public beneficeNet4: number,
        public beneficeNet5: number,
        public amortissement1: number,
        public amortissement2: number,
        public amortissement3: number,
        public amortissement4: number,
        public amortissement5: number,
        public chiffreAffaire1: number,
        public chiffreAffaire2: number,
        public chiffreAffaire3: number,
        public chiffreAffaire4: number,
        public chiffreAffaire5: number,
        public taxes: number,
        public termine: number,
        public remarques: Remarque[],
        public project:Project,
    ) {}
}
